"""baseline

Revision ID: 279508bbe6a0
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 12:35:46.753840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279508bbe6a0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_investments_date'), 'investments', ['date'], unique=False)
    op.create_index('ix_investments_date_amount', 'investments', ['date', 'amount_usd'], unique=False)
    op.create_index(op.f('ix_investments_investor_id'), 'investments', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investments_round'), 'investments', ['round'], unique=False)
    op.create_index(op.f('ix_investments_startup_id'), 'investments', ['startup_id'], unique=False)
    op.create_index('ix_investments_startup_investor', 'investments', ['startup_id', 'investor_id'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    op.create_index(op.f('ix_startups_country'), 'startups', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startups_country'), table_name='startups')
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index('ix_investments_startup_investor', table_name='investments')
    op.drop_index(op.f('ix_investments_startup_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_round'), table_name='investments')
    op.drop_index(op.f('ix_investments_investor_id'), table_name='investments')
    op.drop_index('ix_investments_date_amount', table_name='investments')
    op.drop_index(op.f('ix_investments_date'), table_name='investments')
    # ### end Alembic commands ###
